spring:
  application:
    name: gateway-msc
  cloud:
    gateway:
      mvc:
        routes:
          - id: scraper-service
            uri: ${SCRAPER_SERVICE_URL}
            predicates:
              - Path=/api/v1/scraper/**

server:
  port: ${GATEWAY_PORT}

gateway:
  cors:
    allowed-origins:
      -  "*"
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true
    max-age: 1h
  rate-limit:
    capacity: 100
    refill-tokens: 100
    refill-period: 1m
